jobs:
  include:
    - name: "Linux (glibc) - Node 10"
      os: linux
      dist: trusty
      language: node_js
      node_js: "10"

    - name: "Linux (glibc) - Node 12"
      os: linux
      dist: trusty
      language: node_js
      node_js: "12"

    - name: "Linux (glibc) - Node 14"
      os: linux
      dist: trusty
      language: node_js
      node_js: "14"

    - name: "Linux (musl) - Node 10"
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo docker run -dit --name farmhash --env CI --env CXXFLAGS --env PREBUILD_TOKEN --volume "${PWD}:/mnt/farmhash" --workdir /mnt/farmhash node:10.17.0-alpine3.9
        - sudo docker exec farmhash apk add build-base git python2 --update-cache
      install: sudo docker exec farmhash sh -c "npm install --unsafe-perm"
      script: sudo docker exec farmhash sh -c "npm test"

    - name: "Linux (musl) - Node 12"
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo docker run -dit --name farmhash --env CI --env CXXFLAGS --env PREBUILD_TOKEN --volume "${PWD}:/mnt/farmhash" --workdir /mnt/farmhash node:12.0-alpine
        - sudo docker exec farmhash apk add build-base git python2 --update-cache
      install: sudo docker exec farmhash sh -c "npm install --unsafe-perm"
      script: sudo docker exec farmhash sh -c "npm test"

    - name: "Linux (musl) - Node 12"
      os: linux
      dist: bionic
      language: shell
      before_install:
        - sudo docker run -dit --name farmhash --env CI --env CXXFLAGS --env PREBUILD_TOKEN --volume "${PWD}:/mnt/farmhash" --workdir /mnt/farmhash node:14.0-alpine
        - sudo docker exec farmhash apk add build-base git python2 --update-cache
      install: sudo docker exec farmhash sh -c "npm install --unsafe-perm"
      script: sudo docker exec farmhash sh -c "npm test"

    - name: "OS X - Node 10"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "10"

    - name: "OS X - Node 12"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "12"

    - name: "OS X - Node 14"
      os: osx
      osx_image: xcode9.2
      language: node_js
      node_js: "14"

env:
  global:
    - CXXFLAGS="-march=corei7 -mno-avx -mno-aes -mno-f16c"
